### PR TITLE
 add openReport option - automatically open report when test is finished

### PR DESCRIPTION
**Pull request by aberonni**
View feature request #84 for details

### CODE REVIEW

**Comment by mucsi96** [comment]
Wow! That's very nice! 😃 I'm going to merge it. But I can release it only on Sunday as currently I have no computer access. Thanks for making this package better!

**Comment by aberonni** [comment]
Sounds great - wasn't expecting such a quick merge :smile:

And thank you for making this package in the first place!

**Comment by mucsi96** [comment]
You fix is release in `4.1.0`. Thanks for your patient!

**Comment by aberonni** [comment]
Thank you!

**Pull request merged**
