### PR TITLE
Update nightwatch version

### PR DESCRIPTION
**Pull request by jmkendall**
I saw there was an existing branch that had been closed without a resolution to this.  Submitting a new PR to update nightwatch.

### CODE REVIEW

**Comment by mucsi96** [comment]
Unfortunately such update requires complete rewrite. Because of that I have created a different package as replacement for this called nightwatch-api. Will place a deprecation notice in the readme

**Comment by jmkendall** [comment]
Sounds good.

Thank you

**Comment by Pritchy96** [comment]
Hello @mucsi96, are we to take this package to be deprecated now? Thanks!

**Comment by mucsi96** [comment]
Let me share the new documentation website for my latest project called nightwatch-api. https://nightwatch-api.netlify.com/ 🎉
From Nightwatch.js version 1.0 you are not able to use `nightwatch-cucumber` as a full rewrite is needed. That's why was `nightwatch-api` created. Which is much more lightweight and less hacky :) So I suggest to check it out. I would be very happy to receive any feedback on it. If Nightwatch.js 1.x will be released nightwatch-cucumber will be deprecated.

**Pull request closed without merging**
