### PR TITLE
Add documentation on the Section object

### PR DESCRIPTION
**Pull request by clayreimann**

### CODE REVIEW

**Comment by clayreimann** [comment]
@mucsi96 some documentation for the `Section` object

**Comment by clayreimann** [comment]
@mucsi96 bump cuz it's Monday 😄

**Comment by mucsi96** [comment]
😀👍🙏

**Comment by clayreimann** [comment]
perhaps this and #340 can merge? The only check failing here is codacy (because it can't read the PR)

**Comment by mucsi96** [comment]
Yes. Will do it this week. Sorry for taking it so long :(

**Pull request merged**
