### PR TITLE
[ISSUE-96] fix cucumber after timeout

### PR DESCRIPTION
**Pull request by klokovas**
The options have a timeout field - it is not documented. 
But I assumed that it can be used to set the timeout for cucumber.

In this PR fix for #96.

### CODE REVIEW

**Comment by klokovas** [comment]
I have updated the readme and fixed code style issues.

**Comment by mucsi96** [comment]
Currently your branch is not mergeble. Please merge the master branch

**Comment by klokovas** [comment]
done)

**Comment by mucsi96** [comment]
A new version shoul be released soon automatically.

**Pull request merged**
