### PR TITLE
Fix for bug #161

### PR DESCRIPTION
**Pull request by JonWallsten**
Fixed error where screenshot is not taken due to buffer data is to big to be applied as arguments.

### CODE REVIEW

**Comment by JonWallsten** [comment]
Fix for following issue: https://github.com/mucsi96/nightwatch-cucumber/issues/161

**Comment by JonWallsten** [comment]
@mucsi96 Any change you can take a look at this one? It's a pretty simple fix,

**Comment by mucsi96** [comment]
@JonWallsten sorry for taking this for so long. I was rather busy. I have a problem with your solution. This brings too much string concatenation which should be avoided. Can you propose a different solution?

**Comment by JonWallsten** [comment]
@mucsi96 No worries! Sorry, haven't found any other way of doing it. String concatenation and apply seems to be the two most common solutions.

**Pull request closed without merging**
