### PR TITLE
fix(runner): fix handling multiple tags and skip tags

### PR DESCRIPTION
**Pull request by TylorS**
Currently there is no support for multiple `--tags` in the CLI for cucumberjs so multiple `--tags` lead to only using the last instance of the flag. This means `--tags a --tags b` will effectively be only `--tags b`.

As you can see [here](https://github.com/cucumber/tag-expressions-javascript/blob/master/test/tag_expression_parser_test.js#L9) in the tests for the code that parses the input of `cucumber --tags` it expects a combination of tags separated by `and` or `or` and can be grouped together with parentheses. 

This adds arrelatively straightforward fix for handling multiple items in `nightwatch --tags a` 
and `nightwatch --skiptags a` and when they are both called together as `nightwatch --tags a --skiptags b`.

These are the type of outputs this change will create.

|       CLI options         |       result        |
|----------------------------|--------------------|
| --tags a                     | ( a )                |
| --tags a,b                  | ( a or b )         |
| --skiptags a              | not ( a )           |
| --skiptags a,b           | not (a or b)      |
| --tags a --skiptags b | a and not ( b ) |

---

I'm rather unfamiliar with the tools you're using for testing and how things are setup, even the tests from master were failing for me here locally, please let me know what I can do to get this ready for a merge!

### CODE REVIEW

**Comment by TylorS** [comment]
Hello @mucsi96, thanks for the quick response, as I mentioned earlier I'm really unfamiliar with the test setup. Could you provide me a small nudge in where and what you'd like to see written?

**Comment by mucsi96** [comment]
There are mocha based integration tests in the project. Please check the `test/cli.test.js`. During test execution feature files and step definitions are created. The result is executed with nightwatch-cucumber.

**Comment by TylorS** [comment]
Updated! :smile:

**Comment by mucsi96** [comment]
Yey!!

**Comment by mucsi96** [comment]
Hi @TylorS! I checked [Nightwatch CLI options](http://nightwatchjs.org/guide#command-line-options). There is not options `tests` only test :)

**Comment by TylorS** [comment]
Hello @mucsi96, happy new year! Isn't it `tags` for cucumberjs though? https://github.com/cucumber/cucumber-js/blob/master/docs/cli.md#tags

**Comment by mucsi96** [comment]
Cucumber has `--tags`. But currently we need to execute the nightwatch CLI :( So what about?

| Nightwatch CLI | Cucumber args |
|------------------|------------------|
|`nightwatch --tag a`| `--tags "@a"` |
|`nightwatch --tag a --tag b`| `--tags "@a or @b"` |
|`nightwatch --skiptags a`| `--tags "not(@a)"` |
|`nightwatch --skiptags a,b`| `--tags "not(@a or @b)"` |
|`nightwatch --tag a --skiptags b`| `--tags "@a and not ( @b )"` |

**Comment by mucsi96** [comment]
Just found a Nightwatch PR about `--tags` https://github.com/nightwatchjs/nightwatch/pull/987

**Comment by TylorS** [comment]
@mucsi96 I think that's a great idea :+1:

**Comment by Souji-Asapu** [comment]
@mucsi96 As you mentioned above, the below cucumber args would be --tags "@a or @b" OR --tags "@a AND @b" ?? I believe it should be AND 

Nightwatch CLI	                      |   Cucumber args
                                              |
nightwatch --tag a --tag b    |	  --tags "@a or @b"

**Comment by simonsipl** [comment]
Wouldn't it be better to use `nightwatch -- --tags "@thisTag, ~@notThisTag"` it would be simpler to use ~ as negation

**Comment by mucsi96** [comment]
The feature has landed in the master with #262. Thanks for contribution! Will release soon

**Pull request closed without merging**
